from api.views import (
    change_view,
    change_visibility,
    create_gallery,
    create_promo,
    create_year,
    delete_gallery,
    delete_pic,
    download_pics,
    gallery_reports,
    generate_thumbnails,
    get_expositions,
    get_galleries,
    get_gallery,
    get_pics,
    get_view,
    getRoutes,
    load_folder_into_gallery,
    report_pic,
    years,
)
from django.urls import path

urlpatterns = [
    path("", getRoutes, name="api-routes"),
    path("galleries/", get_galleries),
    path("gallery/load", load_folder_into_gallery),
    path("gallery/gen_thumb", generate_thumbnails),
    path("gallery/pics/", get_pics),
    path("gallery/pics/delete/", delete_pic),
    path("gallery/pics/download/", download_pics),
    path("gallery/pics/report/", report_pic),
    path("gallery/reports/", gallery_reports),
    path("gallery/", get_gallery),
    path("gallery/delete/", delete_gallery),
    path("galleries/create/", create_gallery),
    path("promo/create/", create_promo),
    path("year/create/", create_year),
    path("gallery/change_visibility/", change_visibility),
    path("gallery/change_view/", change_view),
    path("years/", years),
    path("expositions/", get_expositions),
    path("get_view", get_view, name="get_view"),
]
